builds:
    - binary: proxify
      main: cmd/proxify/proxify.go
      goos:
        - linux
        - windows
        - darwin
      goarch:
        - amd64
        - 386
        - arm
        - arm64
      id: proxify

    - binary: replay
      main: cmd/replay/replay.go
      goos:
        - linux
        - windows
        - darwin
      goarch:
        - amd64
        - 386
        - arm
        - arm64
      id: replay

    - binary: mitmrelay
      main: cmd/mitmrelay/mitmrelay.go
      goos:
        - linux
        - windows
        - darwin
      goarch:
        - amd64
        - 386
        - arm
        - arm64
      id: mitmrelay

archives:
    - id: tgz
      format: tar.gz
      replacements:
          darwin: macOS
      format_overrides:
          - goos: windows
            format: zip